### ISSUE TITLE
Type errors that occurred during import

### ISSUE THREAD

**Issue by NotFlyLoongQaQ** [Hiyoteam/hiyobot#1]
Hello, I have some trouble importing this module, my Python version is 3.7.3 64bit, the operating system is Windows 7, the script code is UTF-8, here is my error message.

>Exception has occurred: TypeError
unsupported operand type(s) for |: 'type' and 'type'
  File "C:\Users\Administrator\Desktop\noModBot.py", line 1, in <module>
    import hiyobot

**Comment by 0x24a** [comment]
别整洋文了
非常常见，在py3.8以下不支持|来制定多种类型
已列入TODOs

**Comment by 0x24a** [comment]
请安装最新版本，已修复
